server:
  port: 9005

jwt:
  secret: this is secret

spring:
  application:
    name: auth-service

eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/