server:
  port: 9001

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book-store
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
