
server:
  port: 9002

spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:3306/book-store
    username: root
    password: 1432001Huy@!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
